version: 0.2

phases:
  install:
    commands:
      - pip install pytest
  pre-build:
    commands:
      - pytest
  build:
    commands:
      - pip install --upgrade awscli
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml